USE BancoTpIntegrador;
ALTER TABLE Clientes ADD Estado BOOLEAN DEFAULT 1;
ALTER TABLE Usuarios ADD Estado BOOLEAN DEFAULT 1;
ALTER TABLE Cuentas ADD Estado BOOLEAN DEFAULT 1;
ALTER TABLE Prestamos ADD Estado BOOLEAN DEFAULT 1;